services:
  mongo:
    image: mongo:7
    container_name: spotfoot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1
    container_name: spotfoot-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy

  api:
    build:
      context: ../backend
      target: dev
    container_name: spotfoot-api
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ../backend:/app
      - /app/node_modules
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
